context:
  version: "0.31.1"

package:
  name: dtach
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/d/dtach/dtach-${{ version }}.tar.gz
    sha256: 4802a0d87118bc9a266af15150bfb9516768e2af00bee3ca30bb7c56398ded8e

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - tach = tach.start:start
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.5,<2.0
    - pip
  run:
    - python
    - pyyaml
    - tomli
    - tomli-w
    - rich
    - prompt-toolkit
    - gitpython
    - networkx
    - pydot

tests:
  - python:
      imports:
        - tach
      pip_check: true

about:
  summary: A Python tool to maintain a modular package architecture.
  homepage: https://github.com/DetachHead/dtach
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  description: |+
    # DTach

    > [!IMPORTANT]
    > DTach is a fork of the unmaintained [tach](https://github.com/gauge-sh/tach) project.

    Tach is a Python tool to enforce dependencies and interfaces, written in Rust.

    Tach is inspired by the [modular monolith](https://www.milanjovanovic.tech/blog/what-is-a-modular-monolith) architecture.

extra:
  recipe-maintainers:
    - lucascolley
    - detachhead
